"""domain_packs/common/compliance.py — Compliance metadata for regulated vertical packs."""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Mandatory output disclaimers (overwritten on every response — never LLM-only)
# ---------------------------------------------------------------------------

TALENT_SCREENING_DISCLAIMER = (
    "ASSISTIVE OUTPUT ONLY — NOT A HIRING DECISION. This screening summary is "
    "generated by AI and must not be used as the sole basis for any employment "
    "decision. A qualified human reviewer must evaluate every candidate. "
    "Candidates may have rights regarding automated processing (e.g. GDPR Art. 22, "
    "Québec Law 25, NYC Local Law 144). Operators are responsible for applicable "
    "bias audits, candidate notices, and regulatory compliance (including EU AI Act "
    "high-risk requirements for recruitment AI where applicable)."
)

JOB_DESCRIPTION_WRITER_DISCLAIMER = (
    "ASSISTIVE OUTPUT ONLY — NOT APPROVED FOR PUBLICATION. This job description "
    "draft must be reviewed and approved by HR and legal/compliance before posting. "
    "It may reflect model biases; validate inclusive language and legal requirements "
    "in your jurisdiction."
)

HR_POLICY_QA_DISCLAIMER = (
    "INFORMATIONAL ONLY — NOT LEGAL OR HR ADVICE. Answers are generated from "
    "supplied policy text and may be incomplete or outdated. Employees with rights "
    "regarding automated processing must receive appropriate notice. Escalate to "
    "qualified HR/legal staff for binding interpretations."
)

CONTRACT_REVIEWER_DISCLAIMER = (
    "ASSISTIVE OUTPUT ONLY — NOT LEGAL ADVICE. This contract review is generated by "
    "AI and does not constitute legal counsel. A qualified attorney must review all "
    "commercial agreements before execution."
)

FINANCIAL_MEMO_DISCLAIMER = (
    "SAMPLE/DEMO ONLY — NOT FINANCIAL OR INVESTMENT ADVICE AND NOT A "
    "BANK-COMPLIANT PRODUCT. This memo is a portfolio illustration generated "
    "by AI from fictional or user-supplied context. Do not use it for lending, "
    "trading, client advice, or any regulated decision."
)

_DEFAULT_DISCLAIMERS: dict[str, str] = {
    "talent_screening": TALENT_SCREENING_DISCLAIMER,
    "job_description_writer": JOB_DESCRIPTION_WRITER_DISCLAIMER,
    "hr_policy_qa": HR_POLICY_QA_DISCLAIMER,
    "contract_reviewer": CONTRACT_REVIEWER_DISCLAIMER,
    "financial_memo": FINANCIAL_MEMO_DISCLAIMER,
}

# HR and legal packs stay off. They are kept in the tree so the gate, tests,
# and output guard still exist, but they are not portfolio products.
GATED_PACK_IDS: frozenset[str] = frozenset(
    {
        "talent_screening",
        "job_description_writer",
        "hr_policy_qa",
        "contract_reviewer",
    }
)

# financial_memo is runnable in mock mode. It is labelled sample/demo, still
# injects the disclaimer above, and is not presented as a bank product.
SAMPLE_DEMO_PACK_IDS: frozenset[str] = frozenset({"financial_memo"})

# Integrity scans and strict output validation still cover both sets.
REGULATED_PACK_IDS = frozenset(_DEFAULT_DISCLAIMERS)


def default_disclaimer_for_pack(pack_id: str) -> str | None:
    """Return the built-in disclaimer text for a regulated pack, if any."""
    return _DEFAULT_DISCLAIMERS.get(pack_id)


def regulated_pack_disabled_detail(pack_id: str) -> str:
    """Human-readable 403 detail when a gated HR/legal pack is invoked."""
    return (
        f"Pack {pack_id!r} is disabled in this portfolio fork. "
        "HR and legal packs are not products here. "
        "REGULATED_PACKS_ENABLED does not turn them into a compliance offering "
        "(see the pack's COMPLIANCE.md)."
    )


def assert_regulated_pack_runtime_enabled(
    pack_id: str,
    *,
    regulated_packs_enabled: bool,
) -> None:
    """Raise when a regulated pack is requested without explicit operator opt-in."""
    if pack_id in GATED_PACK_IDS and not regulated_packs_enabled:
        raise ValueError(regulated_pack_disabled_detail(pack_id))


def apply_compliance_output(pack_id: str, data: dict[str, Any]) -> dict[str, Any]:
    """Inject mandatory compliance fields when the pack policy requires human review.

    Disclaimer text comes from ``PackPolicy.compliance_disclaimer`` when set,
    otherwise from :data:`_DEFAULT_DISCLAIMERS`. Values are always overwritten so
    the LLM cannot omit or weaken them.
    """
    from control_plane.registry import PolicyRegistry

    policy = PolicyRegistry.get(pack_id)
    if policy is None or not policy.human_review_required:
        return data

    disclaimer = policy.compliance_disclaimer or default_disclaimer_for_pack(pack_id)
    if not disclaimer:
        disclaimer = (
            "ASSISTIVE OUTPUT ONLY. A qualified human must review this output "
            "before any operational or legal use."
        )

    data["human_review_required"] = True
    data["disclaimer"] = disclaimer
    return data
